# config/packages/prod/monolog.yaml
monolog:
  handlers:
    # this "file_log" key could be anything
    file_log:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: all

    syslog_handler:
      type: syslog
      level: error